#!/bin/sh

#     __               __    _     __   
#    / /_  _________  / /_  (_)___/ /__ 
#   / __ \/ ___/ __ \/ __ \/ / __  / _ \
#  / /_/ (__  ) /_/ / / / / / /_/ /  __/
# /_.___/____/ .___/_/ /_/_/\__,_/\___/ 
#           /_/                         
#
# Hides/unhides focused bspwm node
#
# Written by Nathanael Putro
# Adapted from Ian LeCorbeau's winhide script (https://github.com/I-LeCorbeau/dotfiles/blob/master/.local/bin/winhide)

hidden=$(bspc query --nodes --node .hidden --desktop focused)

if [ -z "$hidden" ]; then
	bspc node focused --flag hidden=on
else
	bspc node "$hidden" --flag hidden=off
fi
