#!/bin/sh

#                          __                            _ 
#    ____ ___  ____ ______/ /_  ____        ____ ___  __(_)
#   / __ `__ \/ __ `/ ___/ __ \/ __ \______/ __ `/ / / / / 
#  / / / / / / /_/ / /__/ / / / /_/ /_____/ /_/ / /_/ / /  
# /_/ /_/ /_/\__,_/\___/_/ /_/\____/      \__, /\__,_/_/   
#                                        /____/
#
# Manual page searcher
#
# Written by Nathanael Putro
# Adapted from HiPhish's macho script (https://hiphish.github.io/blog/2020/05/31/macho-man-command-on-steroids/)

manual=$( \
    apropos -s ${SECTION:-''} ${@:-.} | \
    grep -v -E '^.+ \(0\)' |\
    awk '{print $2 "    " $1}' | \
    sort | \
    rofi -dmenu -i -p "Manual: " | \
    sed -E 's/^\((.+)\)/\1/' \
)

if [ -n "$manual" ]; then
  man -T${FORMAT:-pdf} $manual | ${READER:-zathura} - &
fi
