#!/bin/sh
  
#   ____  ____  ___  ____ 
#  / __ \/ __ \/ _ \/ __ \
# / /_/ / /_/ /  __/ / / /
# \____/ .___/\___/_/ /_/ 
#     /_/                 
#
# MacOS-inspired mimetype-based file opener
# 
# Written by Nathanael Putro
# Adapted from Salman Abedin's launch.sh (https://gist.github.com/salman-abedin/6f52c52e465d89d489f9ea8d891c7332)

# Check for arguments
if [ $# == 0 ]; then
    echo "Usage: open FILE..."
fi

# File array initializations
directory=()
pdf=()
text=()

# Traverse through given files
for file in "$@"
do
    # Check file mimetype
    case $(file --mime-type "$file" --brief --dereference) in
        application/pdf)
            # Open file using preferred application
            pdf+=("$file")
            ;;
        inode/directory)
            directory+=("$file")
            ;;
        text/*)
            text+=("$file")
            ;;
        *)
            echo "Cannot open file \"$file\". Skipping."
            ;;
    esac
done

# Open files in array
if [ ${#directory[@]} -gt 0 ]; then
    spacefm --no-saved-tabs "${directory[@]}" &
fi

if [ ${#pdf[@]} -gt 0 ]; then
    zathura "${pdf[@]}" &
fi

if [ ${#text[@]} -gt 0 ]; then
    nvim -p "${text[@]}"
fi
