#!/bin/sh

#                      __  _ ____     
#    _________  ____  / /_(_) __/_  __
#   / ___/ __ \/ __ \/ __/ / /_/ / / /
#  (__  ) /_/ / /_/ / /_/ / __/ /_/ / 
# /____/ .___/\____/\__/_/_/  \__, /  
#     /_/                    /____/
#
# Spotify launcher
#
# Written by Nathanael Putro

# Ensure spotifyd is running
if [ ! $(pgrep "spotifyd") ]; then
    spotifyd
fi

# Launch spotify-tui
spt
